config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :locations
  resources :comments
  devise_for :users

  # if the user does not have a profile they will be redirected to a page to create one
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  # block resource for links and up/down votes on the links
  # also contains collection for searchkick functionality within links
  resources :links do
    collection do
      get 'search'
    end
  	member do
  		put "like", to:    "links#upvote"
  		put "dislike", to: "links#downvote"
  	end
  	resources :comments
  end

  root to: "links#index"

end

app/models/link.rb
class Link < ActiveRecord::Base
	# searchkick added to model Link for search functionality through Gem
	searchkick
	
	# acts_as_votable added to model Link for voting functionality on each link
	acts_as_votable

	# associations
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { medium: "400x400#", thumb: "400x400>" }
	
	# image regex here for validation on content_type
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	# if the link is destroyed than the location dependent upon it is deleted
  	has_many :locations, :dependent => :destroy
  	# nested form helper to accept locations fields in links form
  	accepts_nested_attributes_for :locations

	# validation set up so no errors appear for missing information
  	validates :title, :url, :image, presence: true

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  # authentication on all methods except index and show pages so non-users cannot just bypass links to edit / destroy content
  before_filter :authenticate_user!, except: [:index, :show]

  def search
    # if the search bar is left blank it will display all the links in the database
    if params[:search].present?
      @links = Link.search(params[:search])
    else
      @links = Link.all
    end
  end


  # GET /links
  # GET /links.json
  def index
    # pulls all links vailable from the database
    @links = Link.all.order("links.updated_at DESC")
    # pulls all the locaton data from the databse to use in the links index page
    @locations = Location.all
    @users = current_user
    @profile = Profile.all

  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    # builds out a link from the current user instead of just a new link
    # @link = Link.new
    @link = current_user.links.build
    # builds an address form-field location for the locations model
    @link.locations.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    # @link = Link.new(link_params)
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    # find link using parameter id
    @link = Link.find(params[:id])
    # send upvote by the current user to db
    @link.upvote_by current_user
    # set redirect to current page
    redirect_to :back
  end

  def downvote
     # find link using parameter id
    @link = Link.find(params[:id])
    # send downvote by the current user to db
    @link.downvote_by current_user
    # set redirect to current page
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # added locations_attributes in link_params to add address from links form to the locations model
    def link_params
      params.require(:link).permit(:title, :url, :image, :blab, locations_attributes: [:address, :_destroy])
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for @link, html: { multipart: true } do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- start of bootsrap styling for form -->
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>

<!-- form for adding address into locations model -->
  <div class="form-group">
    <%= f.fields_for :locations do |builder| %>
    <%= builder.label :address, "Address" %><br>
    <%= builder.text_field :address, class: "form-control" %>
    <% end %>
  </div> 

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :blab %><br>
    <%= f.text_area :blab, class: "form-control" %>
  </div>

  <br>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>


<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<!-- container set to fluid to help bootstrap change style across multi platforms -->
<div class="container-fluid">
  <div class="row">
    <div id="content" class="col-md-8 center-block">
      <% @links.each do |link| %>
        <div class="link row clearfix">
          <%= image_tag link.image.url(:thumb) %>
          <h2>
            <%= link_to link.title, link %><br>
            <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> ago by <%= link_to link.user.name %></small>
          </h2>
        
          <div class="btn-group">
            <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
            <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="glyphicon glyphicon-chevron-up"></span>
              Upvote
              <%= link.get_upvotes.size %>
            <% end %>
            <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
              <span class="glyphicon glyphicon-chevron-down">
              Downvote
              <%= link.get_downvotes.size %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <!-- right hand column of index page set to medium device width 4 bootstrap grid -->
    <div id="content" class="col-md-4 center-block">
      <h4> Blabs Located near you </h4>
      <% @locations.each do |location| %>
        <!-- <div class="link row clearfix"> -->
      <%= location.link.title %> @ <%= link_to location.address, location %><br>
      

      <%end %>
    </div>
  </div>
</div>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/search.html.erb
<h1>Searched Blabs</h1>

<div class="row">
  <% @links.each do |link| %>
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag link.image.url(:medium), class: 'image'), link %>
        <small class="author"><%= link.title %> by <%= link_to link.user.name %> </small>
      </div>
    </div>
  <% end %>
</div>

app/views/links/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @link.image.url(:medium) %>
    </div>
    
    <div class="col-md-4">
        <h2> What's the Blab? </h2>
      <p>
        <%= @link.blab %>
      </p>
    </div>
  <div>


  <div class="row">
    <div class="col-md-12 center-block">
      <!-- header styling using bootstrap -->
      <div class="page-header">
      	<h1><a href="<%= @link.url %>"><%= @link.title %></a><br> <small>submitted by <%= @link.user.name %></small></h1>
      </div>

      <!-- All users can see link button on posts -->
      <div class="btn-group">
      	<%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
      </div>

      <!-- like dislike methods / buttons -->

      <div class="btn-group pull-right">
        <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= @link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down">
          Downvote
          <%= @link.get_downvotes.size %>
        <% end %>
      </div>

      <!-- authorisation showing edit and destroy buttons for user if they created the post -->
      <% if @link.user == current_user %>
      	<div class="btn-group">
      		<%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
      		<%= link_to 'Destroy', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
      	</div>
      <% end %>

      <!-- comments section -->

      <h3 class="comments_title">
        <!-- counts amount of comments for the particular link -->
        <%= @link.comments.count %> Comments
      </h3>

      <div id="comments">
        <%= render :partial => @link.comments %>
      </div>

      <!-- simple form for adding a comment -->
      <%= simple_form_for [@link, Comment.new]  do |f| %>
        <div class="field">
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <br>
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>