config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :locations
  resources :comments
  devise_for :users

  # if the user does not have a profile they will be redirected to a page to create one
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  
  # block resource for links and up/down votes on the links
  # also contains collection for searchkick functionality within links
  resources :links do
    collection do
      get 'search'
    end
  	member do
  		put "like", to:    "links#upvote"
  		put "dislike", to: "links#downvote"
  	end
  	resources :comments
  end

  root to: "links#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blabr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- bootstrap styling for navbar -->
	<header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Blabr", root_path %></div>
	        <div class="collapse navbar-collapse navbar-ex1-collapse">
	        	<!-- authorisation to only show logged in user options -->
	        	<% if user_signed_in? -%>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to 'Submit link', new_link_path %></li>
	        			<li class="dropdown">
	          				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
	          				<ul class="dropdown-menu">
								<li><%= link_to 'Edit Account', edit_user_registration_path %></li>
								<li><%= link_to 'Profile', profile_path(current_user) %></li>
								<li><%= link_to 'Edit Profile', edit_profile_path(current_user) %></li>
							</ul>
						</li>
						<li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
					</ul>
				<% else %>
					<ul class="nav navbar-nav pull-right">
						<li><%= link_to 'Sign up', new_user_registration_path %></li>
						<li><%= link_to 'Sign in', new_user_session_path %></li>
					</ul>
				<% end %>
				<%= form_tag search_links_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
					<p>
						<%= text_field_tag :search, params[:search], class: "form-control" %>
						<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
					</p>
				<% end %>
	        </div>
      </div>
    </div>
  </header>

	<!-- bootstrap alert styling -->
	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<!-- bootstrap center-block yield / content -->
		<div id="content" class="col-md-12 center-block">
			<%= yield %>
		</div>
	</div>
</div>


<!-- footer development using bootstrap -->
<footer class="footer">
	<div class="panel-footer">
		<div class="wrap">
		  <small>
		    Brought to you by <a href="http://www.taxitoursireland.ie/">Taxitoursireland.</a>
			Developed with love by <a href="http://www.iambradley.me/">Bradley.</a>
		  </small>
		  <li class="nav navbar-nav navbar-right">
		     <%= link_to "About",   root_path %> |
		     <%= link_to "Contact", root_path %> | 
		     <a href="http://www.taxitoursireland.ie/">News &nbsp;</a>  
		  </li>
		</div>
	</div>
</footer>
</body>
</html>